### ISSUE TITLE
Translucency thickness bad default

### ISSUE THREAD

**Issue by andylbn** [bdancer/plugins_desc#1]
{
            "attr": "translucency_thickness",
            "default": 1000000000000000000.0, **`// shud be other!`**
            "desc": "Maximum distance to trace inside the object",
            "type": "FLOAT",
            "ui": {
                "max": 1048576,
                "min": -1048576,
                "soft_max": 64,
                "soft_min": 0,
                "display_name": "Thickness",
                "enabled": true
            }
        },

**Comment by bdancer** [comment]
@andylbn your suggestion?

**Comment by andylbn** [comment]
1000 is good value for default
